server:
  port: 8099
#  ssl:
#    key-store: classpath:keystore.p12
#    key-alias: tomcat
#    enabled: true
#    key-store-password: 123456
#    key-store-type: PKCS12

#
######## mysql连接的配置 start########
#mysql主的读写支持
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ymt_test?useSSL=false&serverTimezone=UTC
    username: root
    password: 107077
    tomcat:
      max-active: 40
      max-idle: 20
    driver-class-name: com.mysql.jdbc.Driver
  jpa.show-sql: true
#spring.jpa.properties.hibernate.hbm2ddl.auto=update//该部分禁止开启
######## mysql连接的配置 end########
#
#
############自定义属性####################
myproperties:
  name: ymt
#